---
- name: Second project
  hosts: webservers
  become: true
  vars:
    redmine_image: redmine:5.1.2
    redmine_container_name: redmine
    redmine_env_file: .env.redmine

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker

  tasks:
    - name: Create .env for Redmine
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: "{{ ansible_user_dir }}/{{ redmine_env_file }}"
        mode: '0600'
      tags: deploy

    - name: Stop and remove old Redmine container
      community.docker.docker_container:
        name: "{{ redmine_container_name }}"
        state: absent
      failed_when: false
      tags: deploy

    - name: Run Redmine container
      community.docker.docker_container:
        name: "{{ redmine_container_name }}"
        image: "{{ redmine_image }}"
        env_file: "{{ ansible_user_dir }}/{{ redmine_env_file }}"
        ports:
          - "{{ redmine_port }}:3000"
        restart_policy: always
        state: started
      tags: deploy

    - name: Import the Datadog Agent role from the Datadog collection
      ansible.builtin.import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: "{{ DATADOG_API_KEY }}"
        datadog_site: "us3.datadoghq.com"
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: devops1 app health
                url: http://212.233.92.143:3000/
              - name: devops2 app health
                url: http://212.233.95.46:3000/
